version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: Product.API/Dockerfile
      
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/Product.Domain/products.db
    depends_on:
      - db
    volumes:
      - sqlite-data:/app/Product.Domain

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_strong_Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

volumes:
  sqlite-data:
