version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/products.db;  
    volumes:
      - /Users/rozhanalvandi/Documents/GitHub/Product/Product:/data  
    command: >
      /bin/bash -c "dotnet ef database update && dotnet Product.dll"